config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :hugs
end

app/models/hug.rb
class Hug < ActiveRecord::Base
	belongs_to :receiver, class_name: "User"
	belongs_to :giver, class_name: "User"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :received_hugs, class_name: "Hug", foreign_key: :receiver_id
	has_many :given_hugs, class_name: "Hug", foreign_key: :giver_id

	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hugs_controller.rb
class HugsController < ApplicationController
	before_action :set_hug, only: [:show, :edit, :update, :destroy]

  # GET /hugs
  # GET /hugs.json
  def index
    @hugs = Hug.all
  end

  # GET /hugs/1
  # GET /hugs/1.json
  def show
  end

  # GET /hugs/new
  def new
    @hug = Hug.new
  end

  # GET /hugs/1/edit
  def edit
  end

  # POST /hugs
  # POST /hugs.json
  def create
    @hug = Hug.new(hug_params)
    @hug.giver = User.find(session[:user_id])

    respond_to do |format|
      if @hug.save
        format.html { redirect_to hugs_path, notice: 'Hug was successfully created.' }
        format.json { render :index, status: :created, location: @hug }
      else
        format.html { render :new }
        format.json { render json: @hug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hugs/1
  # PATCH/PUT /hugs/1.json
  def update
    respond_to do |format|
      if @hug.update(hug_params)
        format.html { redirect_to @hug, notice: 'Hug was successfully updated.' }
        format.json { render :show, status: :ok, location: @hug }
      else
        format.html { render :edit }
        format.json { render json: @hug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hugs/1
  # DELETE /hugs/1.json
  def destroy
    @hug.destroy
    respond_to do |format|
      format.html { redirect_to hugs_url, notice: 'Hug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hug
      @hug = Hug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hug_params
      params.require(:hug).permit(:giver, :receiver, :appointment, :special_requests)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
	end

	def create
		data = params[:user]
		@user = User.find_by(email: data[:email]).try(:authenticate, data[:password])
		if @user 
			session[:user_id] = @user.id
			redirect_to hugs_path
		else
			format.html { render :new }
		end
	end

	def destroy
		session.clear
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :email, :hugger_type, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	include ApplicationHelper
	def index
		current_user
		if @current_user
			redirect_to hugs_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
    if session[:user_id]
      @current_user ||= User.find session[:user_id]
    end
  end
end

app/helpers/hugs_helper.rb
module HugsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hugs/_form.html.erb
<%= form_for(@hug) do |f| %>
  <% if @hug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hug.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @hug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appointment %><br>
    <%= f.date_field :appointment %>
  </div>
  <div class="field">
    <%= f.label :special_requests %><br>
    <%= f.text_field :special_requests %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hugs/index.html.erb
<h1>Welcome to the Hugging is Caring App</h1>

<table>
  <thead>
    <tr>
      <th>Hug Giver</th>
      <th>Date</th>
      <th>Special Requests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hugs.each do |hug| %>
      <tr>
        <td><%= hug.giver.username %></td>
        <td><%= hug.appointment.strftime("%F") %></td>
        <td><%= hug.special_requests %></td>
        <td><%= link_to 'Show', hug %></td>
        <td><%= link_to 'Edit', edit_hug_path(hug) %></td>
        <td><%= link_to 'Destroy', hug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create A Hug Appointment', new_hug_path %>

app/views/hugs/new.html.erb
<h1>Want to give a hug? It means you care!</h1>

<%= render 'form' %>

<%= link_to 'Back', hugs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hugs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :hugger_type %><br>
    <%= f.text_field :hugger_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Welcome to the Hugging is Caring App</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th>Email</th>
      <th>Hugger type</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.email %></td>
        <td><%= user.hugger_type %></td>
        <td><%= user.description %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create A Hug Appointment', new_hug_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Hugger type:</strong>
  <%= @user.hugger_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to the Hugging Is Caring app</h1>

<ul>
	<li><%= link_to 'Log in', new_session_path %></li>
	<li><%= link_to 'New User', new_user_path %></li>
</ul>